### ISSUE TITLE
Web Application 

### ISSUE THREAD

**Issue by warpdriv** [lecode-official/deepl-dotnet#11]
Hi,

Thank you for putting together this library.

I am trying to get my code working with the nuget package. I am using it in an .net web forms app. When I run this code sends the request and waits (because I need to do something with afterwards). However, when I run my project in debug, the request never comes back so I terminate the run. I have tried to model my code off this site and the example project.

Thank you for your help.

        public List<SRTInfo> GetTranslations(List<SRTInfo> lstText, string lang)
        {
            Debug.WriteLine("starting");

            string text = lstText[0].originalText;

            var tTranslate = TranslateText(text, lang.ToUpper());
            Debug.WriteLine("waiting");

            tTranslate.Wait();

            return lstText; // return what is sent until working
        }

        public static async Task TranslateText(string text, string lang)
        {
            Debug.WriteLine("got here");

            using (DeepLClient client = new DeepLClient(apiKey, useFreeApi: false))
            {
                try
                {
                    Translation translation = await client.TranslateAsync(
                        "This is a test sentence.",
                        lang.ToUpper()
                    );

                    Debug.WriteLine(translation.DetectedSourceLanguage);
                    Debug.WriteLine(translation.Text);
                }
                catch (DeepLException exception)
                {
                    Debug.WriteLine($"An error occurred: {exception.Message}");
                }
            }
            Debug.WriteLine("leaving");

        }

**Comment by lecode-official** [comment]
Hi @warpdriv,

I am no expert at the internals of Tasks, but it could be, since ASP.NET only has Thread on which the request is handled, that there is already another background task on the main thread by the time the task completes. Since the task is configured to return execution to the main thread it hangs. Can you try calling `ConfigureAwait(false)` on the task like so: 

`Translation translation = await client.TranslateAsync("This is a test sentence.", lang.ToUpper()).ConfigureAwait(false);`

**Comment by lecode-official** [comment]
I have read a little more on the topic and stumbled upon this blog post, which beautifully explains this problem: https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html. I believe that the solution I send you earlier should fix the deadlock, but the blog post will explain much better what is happening.

**Comment by warpdriv** [comment]
Hi David,

Thank you for the quick responses. I did some more research based on the
information you gave me and some testing. I still cannot get this to work.
I even created a new web app project and pulled in your project (from a git
clone). Sorry to say (because I like your implementation) and since I'm on
a tight deadline, I am switching to RestSharp. If you get a web app example
going please let me know.

Again, thank you for your help.

Best Regards,
Jeff

**Comment by lecode-official** [comment]
Hi @warpdriv,

I am really sorry to hear that I could not solve your problem. I have read a little more about the problem, an Microsoft specifically sates that all library authors should (almost always) use `ConfigureAwait(false)` in their libraries. First of all this brings some performance benefits and secondly it fixes deadlock issues similar to yours. Therefore, I will, when I find some time, release a new version of DeepL.NET, were `ConfigureAwait(false)` is used everywhere. I'll tell you when the new version is on NuGet, if you want to, you can give it one more try, then.

**Comment by warpdriv** [comment]
Hi David,

Thank you for the update.

It seems, at least what I read, threading and async process escapes most
people, like me. :) If I may suggest, could you please create a simple web
form (non-mvc) project that takes a text box input, translates it, and they
displays the translation in a label? It would be very helpful to me to help
me understand what is going on.

Thank you again for all your efforts.

Jeff

**Comment by lecode-official** [comment]
Hi @warpdriv,

I am really sorry that I only answer now. I would love to provide more samples on how to use the library, but I have never used web forms before. Can you please create a very basic stump project with the text box and label? Then I can fiddle around with it to integrate DeepL.NET.

**Comment by warpdriv** [comment]
Hi David,

Thank you for getting back with me. I'm happy to help.

Please use the google drive link to download the web project. The
Utils.DeelLTranslate class will need to be modified for your api key.

https://drive.google.com/file/d/18FzOTz86q6evuZSRRdmfE19z_5hNUPko/view?usp=sharing

Please let me know if you have any questions.

Regards,
Jeff

**Comment by lecode-official** [comment]
Hi @warpdriv,

thank you for your sample, unfortunately, I do not have access to the files. I send you an access request.

**Comment by warpdriv** [comment]
Hi David,

I just granted you access. Please let me know if you have any questions.

Regards,
Jeff

**Comment by lecode-official** [comment]
Hi Jeff,

I am really sorry for letting you wait for so long. This probably won't be relevant for you anymore, but I have had a look at your sample application today. I installed the latest version of the DeepL package and altered your code in the `DeepLTranslate.cs` file like so and it works for me:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeepL;
using Newtonsoft.Json;
using RestSharp;


namespace DeepLExample.Utils
{
    public class DeeplResponse
    {
        public List<DeeplTranslations> translations { get; set; }
    }
    public class DeeplTranslations
    {
        public string detected_source_language { get; set; }
        public string text { get; set; }
    }

    public class DeepLTranslate
    {
        public List<string> GetTranslations(List<string> lstText, string lang)
        {

            int cntList = lstText.Count;
            int segementCounter = 0; // tracking for loading translation responses

            List<string> lstOriginalText = new List<string>();

            for (int i = 0; i < cntList; i++)
            {
                lstOriginalText.Add(lstText[i]);

                // limit number of translation request; the API can only take so much
                if (i % 1000 == 0 || i == cntList - 1)
                {
                    List<Translation> translations = CallDeepl(lstOriginalText, lang.ToUpper()).ToList();

                    try
                    {
                        int cntDr = translations.Count;

                        for (int x = 0; x < cntDr; x++)
                        {
                            lstText[segementCounter] = translations[x].Text;
                            segementCounter++;
                        }
                        lstOriginalText.Clear();
                    }
                    catch
                    {
                        throw new Exception(); // this will thow the message from the 
                    }
                }
            }

            return lstText;
        }

        protected IEnumerable<Translation> CallDeepl(List<string> lstText, string lang)
        {
            using (DeepLClient client = new DeepLClient("<authentication-key>", useFreeApi: true))
            {
                Task<IEnumerable<Translation>> task = client.TranslateAsync(lstText, lang);
                task.Wait();
                IEnumerable<Translation> translations = task.Result;
                return translations;
            }
        }
    }
}
```

Since it seems to work, even when using Wait(), I will close this issue for now, but if you have anymore questions, then feel free to reopen this issue or create a new one. I promise I will be faster next time.

Regards
David
